### ISSUE TITLE
 E:/work/seed-project/portfolio/src/app/app.module.ts (26,9): Cannot find name 'ParallaxConfig'.)

### ISSUE THREAD

**Issue by rishabhrawat11** [cwadrupldijjit/ng2-parallax#10]
I don't know why It can't find the interface even tho It can find Parallax class but not the ParallaxConfig

**Comment by cwadrupldijjit** [comment]
Could I get more details, such as code snippets or steps to reproduce the bug?  I get the idea of what you're dealing with, but for all I know it could be an issue with your reference to the directive or an issue in the typescript compile phase, or something.

**Comment by cwadrupldijjit** [comment]
I've not heard back about this in a while and at the current moment am not sure if this really is a bug in the package.  Closing this for now.  If you have any more issues like this, feel free to open it in the new repo:
[cwdj-parallax](https://github.com/cwadrupldijjit/cwdj-parallax)
