### ISSUE TITLE
Broken link with examples

### ISSUE THREAD

**Issue by kaweski** [cwadrupldijjit/ng2-parallax#15]
The link of the page with examples is broken and cannot be reached.
Could you provide another link, please?

**Comment by cwadrupldijjit** [comment]
@naweskil: Check it out now.  It should be up and running.  I'm not sure why it died.

**Comment by flomllr** [comment]
It seems to be broken again.

**Comment by cwadrupldijjit** [comment]
This has been fixed, though I also created a new repo for this component that is not outdated as this component is.  You can find it here:
https://github.com/cwadrupldijjit/cwdj-parallax
