### ISSUE TITLE
Workflow to publish js files

### ISSUE THREAD

**Issue by MurhafSousli** [cwadrupldijjit/ng2-parallax#6]
hi @cwadrupldijjit, I'm using a new workflow to publish angular packages to npm as pre compiled js with ngc, which supports AOT.
If you would like to ship js files to npm, I can create a pull request for the `gulpfile.js` and then the steps are straight forward: 

1 - increment package version
2 - build with gulp
```
gulp build 
```
3 - publish `dist` to npm
```
npm publish ./dist
```

**Comment by cwadrupldijjit** [comment]
I'd be interested in seeing those changes.  Go ahead!

**Comment by cwadrupldijjit** [comment]
Closing this as the PR was put in and forgotten in time.  There has been a change to the setup of the package, and even a new package released since then.  Questions about it should be created in a new issue there:
[cwdj-parallax](https://github.com/cwadrupldijjit/cwdj-parallax))
