### ISSUE TITLE
App Module works just fine with angular-cli

### ISSUE THREAD

**Issue by kirikintha** [cwadrupldijjit/ng2-parallax#9]
Hey there, I am installing this on a new angular-cli project, and I had to use the app module to load this. It seems to be loading fine, and webpack has no issue. Just thought you should know!

```
import { Parallax,
         ParallaxConfig } from 'ng2-parallax/commonjs';
@NgModule({
  declarations: [
    AppComponent,
    Parallax
  ]
  ...
})
export class AppModule { }
```

**Comment by crutchcorn** [comment]
Same for me, I would suggest making a change to the README dismissing the issues with Webpack

**Comment by cwadrupldijjit** [comment]
It used to have issues, but I'm grateful that they have been fixed.

I'll remove that when I have a second to check it out.

**Comment by cwadrupldijjit** [comment]
This has been updated and fixed with the changes I made to upgrade it from the half-working state from Angular 2 beta.  I'll close this issue for now, but if it still fails, feel free to open it up in the new repo:
[cwdj-parallax](https://github.com/cwadrupldijjit/cwdj-parallax)
